#!/bin/bash
TEXTO=$(cat ejemplo.txt)
for palabra in $TEXTO
do
	if [ ${#palabra} -gt 4 ];
	then
		PALABRA=$(echo $palabra | tr -d ["."","" "";"])
		echo "'$PALABRA' aparece $(grep -o -i $palabra ejemplo.txt | wc -l) veces"
	fi
done


