#!/bin/bash

opc=0

while [ $opc -ne 6 ]; do

clear

echo "1- Indicador estadístico de longitud de palabras "
echo "2- Indicador estadístico de uso de palabras "
echo "3- Identificación de nombres propios"
echo "4- Indicador estadístico de longitud de oraciones"
echo "5- Contador de lineas en blanco"
echo "6- Salir"
echo
read -p "Seleccione una opcion: " opc

case $opc in

    1) clear 
        echo Se ejecutara el Indicador estadístico de longitud de palabras
        echo
        echo
        ./statsWords.sh
        sleep 7 
        ;;
    2) clear 
        echo Se ejecutara el Indicador estadístico de uso de palabras
        echo
        echo
        ./statsUsageWords.sh
        sleep 7
        ;;
    3) clear 
        echo Se ejecutara la Identificación de nombres propios
        echo
        echo
        ./findNames.sh
        sleep 7 
        ;;
    4) clear 
        echo Se ejecutara el Indicador estadístico de longitud de oraciones
        echo
        echo
        ./statsSentences.sh
        sleep 15
        ;;
    5) clear 
        echo Se ejecutarar el Contador de lineas en blanco
        echo
        echo
        ./blankLinesCounter.sh
        sleep 7
        ;;
    6) clear 
        ;;
    *)echo $opc no es una opcion valida. Ingrese una nueva 
	    sleep 4
        ;;  

esac

done
